import Link from "next/link";
import Image from "next/image";
import type { Project } from "@/lib/projects";
import { BackPixelIcon } from "./BackPixelIcon";
import { ProjectContents } from "./ProjectContents";
import { MemorythreadHero } from "./MemorythreadHero";
import { MemorythreadBuildLoop, MemorythreadCarousel } from "./MemorythreadMotion";
import shared from "@/app/projects/[slug]/page.module.css";
import styles from "./MemorythreadCaseStudy.module.css";

const sections = ["Overview", "Background", "First build", "AI iteration", "Feedback", "Final design", "Reflection"].map(label => ({id:label.toLowerCase().replaceAll(" ", "-"), label}));
function Section({id, label, children}: {id:string; label:string; children:React.ReactNode}) {
  return <section id={id} className={styles.section}><span className={styles.label}>{label}</span><div className={styles.sectionBody}>{children}</div></section>;
}
function Recording({src, caption}: {src:string; caption:string}) {
  return <figure className={styles.recording}><video controls playsInline preload="metadata" src={src} aria-label={caption}/><figcaption>{caption}</figcaption></figure>;
}
export function MemorythreadCaseStudy({next}: {next:Project}) {
  return <section className={`${shared.page} ${styles.page}`}><article className={styles.body}>
    <Link href="/" className={shared.back}><BackPixelIcon/>Projects</Link>
    <header id="overview" className={styles.header}><h1>Helping families turn a shared cue<br/>into their next question.</h1><p>A family conversation app that suggests questions from photos or shared topics and connects stories about the people mentioned.</p></header>
    <MemorythreadHero/>
    <div className={styles.intro}><div className={styles.lede}><p>I built an AI-connected prototype, then redesigned how both family members could shape the conversation.</p></div><dl className={styles.metadata}><div><dt>Timeline</dt><dd>December · 2 weeks<br/>February–March · 4 weeks<br/>May · 2 weeks</dd></div><div><dt>My role</dt><dd>Solo product designer<br/>Interaction design, AI-assisted implementation, physical tile prototype</dd></div><div><dt>Build</dt><dd>V1 · Claude, React, OpenAI API, Vercel<br/>V2–V3 · Lovable</dd></div><div><dt>Status</dt><dd>Working web prototype<br/>Physical sensing board is a concept</dd></div></dl></div>
    <Section id="background" label="Background"><div className={styles.reading}><h2>A family wanted to hear more.<br/>Where could the conversation begin?</h2><p>A Korean-American learner I tutored wanted to hear about their mother’s life before immigration. Their mother was living with dementia, and they didn’t know enough about her life or her home country to know what to ask. The conversation kept circling the little they already knew.</p></div><aside className={styles.callout}><span className={styles.eyebrow}>My starting hypothesis</span><p>A family photo could give them something concrete to talk about. AI could help the family find a first question and a follow-up.</p></aside></Section>
    <Section id="first-build" label="First build"><h2>I built the whole loop with Claude.</h2><p className={styles.reading}>Upload a photo, generate a question, capture an answer, and build a memory map.</p><span className={styles.diagramLabel}>How it works · Illustrative</span><MemorythreadCarousel label="How it works" slides={[
      ["photo-concept.png", "Sit together", "A senior storyteller and a family member sit in front of the computer with photos ready to talk about."],
      ["v1-upload.png", "Upload a photo", "Upload a prepared photo."],
      ["v1-question.png", "Start with a question", "AI tailors a question to the photo."],
      ["v1-answer.png", "Capture the answer", "The storyteller answers, and Memory Thread records it."],
      ["v1-followup.png", "Follow the story", "Based on that answer, AI generates a follow-up question."],
      ["v1-map.png", "Return through the Memory Map", "AI extracts keywords from the conversation and adds them to a Memory Map. Select a keyword to revisit related conversations and an AI summary."],
    ].map(([src, title, caption]) => ({src: `/images/memorythread/${src}`, title, caption, alt: caption}))}/><div className={styles.buildLayout}><span className={styles.diagramLabel}>How I built and iterated with Claude</span><MemorythreadBuildLoop/></div></Section>
    <Section id="ai-iteration" label="AI iteration"><h2>The AI recognized the photo,<br/>but its questions stayed generic.</h2><p>The answer mentioned someone bringing flowers. The AI stayed with the object instead of exploring the person and the situation.</p><div className={styles.questionDiagram} aria-label="The same answer leads to two different follow-up directions"><div className={styles.questionSource}><span className={styles.eyebrow}>The answer</span><strong>Someone brought flowers.</strong></div><div className={styles.questionBranches}><div><span className={styles.eyebrow}>Problem · stays with the object</span><blockquote>“Do you like flowers?”</blockquote><p>The AI asked simple questions.</p></div><div><span className={styles.eyebrow}>My request · explore who and why</span><blockquote>“Who brought the flowers?”<br/>“Why did they bring them?”</blockquote><p>Ask who was involved and why, using the answer’s context.</p></div></div></div><p className={styles.note}>Reconstructed examples show the requested direction. I retested the same photo and answer and observed more specific extracted keywords. That did not establish better follow-up questions.</p></Section>
    <Section id="feedback" label="Feedback"><h2>Feedback pushed me to rethink each person’s role.</h2><p className={styles.reading}>I demonstrated the prototype to five designers at junior, mid-level, and senior levels. Their feedback prompted me to reconsider each person’s role.</p><div className={styles.decision}><span className={styles.eyebrow}>V1 → V2 · First round of feedback</span><blockquote>“What does the older adult do while their guardian is typing?”</blockquote><h3>Let the storyteller choose the starting topic</h3><p>I added physical topic tiles so the storyteller could choose what to talk about. A photo became optional, opening a way to begin with a person, place, or time.</p><div className={styles.comparison}><div><span className={styles.eyebrow}>V1 · Photo-led</span><ol className={styles.roleSteps}><li><small>Family member</small>Uploads a photo</li><li><small>Family member</small>Asks a suggested question</li><li><small>Storyteller</small>Answers</li></ol></div><div><span className={styles.eyebrow}>V2 · Storyteller-led</span><ol className={styles.roleSteps}><li><small>Storyteller</small>Selects topic tiles</li><li><small>Family member</small>Scans and asks</li><li><small>Storyteller</small>Shares</li></ol></div></div><p>After the first round of feedback, I designed V2 around the storyteller choosing physical topic tiles. The family member would scan the tiles and guide the conversation. Tile recognition was simulated.</p><div className={styles.entryRow}><figure><Image src="/images/memorythread/v2-concept.png" width={432} height={295} alt="Earlier triangular tile concept illustration"/><figcaption>Earlier triangular-tile concept · AI-generated illustration. This depicts the proposed use scenario, not the physical prototype or a user test.</figcaption></figure><figure><Image src="/images/memorythread/v2-tiles-still.png" width={470} height={295} alt="Triangular topic tiles arranged on a table"/></figure></div><Recording src="/images/memorythread/v2-tiles.mp4" caption="V2 tile prototype walkthrough. Tile recognition was simulated."/></div><div className={styles.decision}><span className={styles.eyebrow}>V2 → V3 · Second round of feedback</span><blockquote>“Is the granddaughter only there to type?”</blockquote><h3>Let both people choose the starting topic</h3><p>After seeing V2, a senior designer and a colleague asked whether the granddaughter was only there to type. I added shared topic selection so she could suggest what to explore, while still managing questions, recording, and saving.</p><aside className={styles.callout}><p>Both can propose a topic. The family member still manages the app.</p></aside></div></Section>
    <Section id="final-design" label="Final design"><h2>Start together.<br/>Build a conversation to return to.</h2><div className={styles.entryRow}><figure><Image src="/images/memorythread/photo-concept.png" width={1536} height={1024} alt="Concept illustration of a storyteller and family member sharing a photo"/><figcaption>AI-generated concept illustration</figcaption></figure><div><h3>Start with a photo</h3><p>Bring a family photo into the conversation. Look at it together and choose what to ask.</p></div></div><div className={styles.entryRow}><div><h3>Start with tiles</h3><p>Choose topics together when starting without a photo. Either person can suggest a person, place, or time.</p></div><figure><Image src="/images/memorythread/shared-topics.png" width={1536} height={1024} alt="Two family members placing topic tiles together in a concept illustration"/><figcaption>AI-generated concept illustration · board sensing is simulated</figcaption></figure></div><div className={styles.roles}><div><span className={styles.eyebrow}>Storyteller</span><h3>Chooses what to share</h3><p>Can change or decline a topic.</p></div><span className={styles.roleArrow} aria-hidden="true">↔</span><div><span className={styles.eyebrow}>Family member</span><h3>Asks and operates</h3><p>Chooses topics with the storyteller, asks questions, and manages recording and saving.</p></div><p className={styles.aiSupport}><strong>AI support</strong> Photos or topic cues + answers → suggested questions.<br/>Saved answers → memory details and summaries.</p></div><div className={styles.decision}><span className={styles.eyebrow}>02 · Talk together</span><h3>Follow the answer into the next question</h3><p>The family member asks an AI-suggested question or one of their own. The storyteller answers aloud; voice input or typing captures the response.</p><Recording src="/images/memorythread/v3-questions.mp4" caption="V3 conversation walkthrough · recorded prototype interaction."/></div><div className={styles.decision}><span className={styles.eyebrow}>03 · Return to a story</span><h3>Find related conversations through the Memory Map</h3><p>AI extracts keywords from the conversation into the Memory Map. Select a person, place, or time to revisit related conversations and an AI summary.</p><Recording src="/images/memorythread/v3-map.mp4" caption="V3 Memory Map walkthrough · recorded prototype interaction."/><p className={styles.note}>The current prototype stores conversations in this browser. Cross-device family syncing and physical-board sensing are not connected.</p></div></Section>
    <Section id="reflection" label="Reflection"><h2>What building an AI product taught me</h2><div className={styles.reflections}><div><h3>Recognizing the photo was not enough</h3><p>The AI recognized flowers, but “Do you like flowers?” moved away from the story. I learned to use the answer—not just the image—to guide questions about who brought them and why.</p></div><div><h3>Shared topics did not remove the operator role</h3><p>V3 lets both people choose topics, but the family member still manages questions and recording. I learned to distinguish sharing control of the conversation from sharing control of the app.</p></div></div><p className={styles.closing}>Building with Claude let me move from an idea to behavior I could inspect. I learned to give specific feedback, rerun the same inputs, and distinguish what I observed from what I hoped would improve.</p></Section>
    <Link href={`/projects/${next.id}`} className={shared.next}><span><small>Next project</small><strong>{next.title}</strong></span><span className={shared.nextArrow}><BackPixelIcon/></span></Link>
  </article><ProjectContents sections={sections}/></section>;
}
